/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;


public class ClientesTest {
    @Test
    public void clienteTest() {
       Clientes clientes = new Clientes("Josele","A",10000);
       int actual=clientes.totalPagarA("A");
       int expect=500;
       Assert.assertEquals(expect,actual);
    }

    @Test
    public void cienteTest(){
        Clientes clientes = new Clientes("Mariano","B",10000);
        int actual=clientes.totalPagarB("B");
        int expect=250;
        Assert.assertEquals(expect,actual);
    }

    @Test
    public void cienteTest1(){
        Clientes clientes = new Clientes("Jorge","C",10000);
        int actual=clientes.totalPagarC("C");
        int expect=100;
        Assert.assertEquals(expect,actual);
    }

    @Test
    public void clienTestfailed(){
        Clientes clientes = new Clientes("Jorge","C",10000);
        int actual=clientes.totalPagarC("C");
        int expect=100;
        Assert.assertEquals(expect,actual);
    }
}