/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

public class ContadorTest {
    @Test
    public void contadorIncremento() {
        Contador contador = new Contador(5, 5);
        int expect= 5;
        int actual= contador.incrementoContador(5);
        Assert.assertEquals(expect,actual);
    }
    @Test
    public void contadorDecremento(){
        Contador contador = new Contador(5, 5);
        int expect= -10;
        int actual= contador.decrementoContador(10);
        Assert.assertEquals(expect,actual);
    }
}