/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;


public class ElectrodomesticoTest {
    @Test
    public void contadorIncremento() {
        Electrodomestico electrodomestico = new Electrodomestico("Samsung","Refigerador","balnco",50,"2 años");
        Electrodomestico electrodomestico1 = new Lavadora("Samsung","Lavadora","rojo",60,"2 años",100);
        Electrodomestico electrodomestico2 = new Licuadora("Samsung","Licuadora","Azul",20,"2 años",10);

        electrodomestico1.get_capacidadMax(90);
    }
}