/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;


public class EmpleadoTest {
    @Test
    public void empleadoTest() {
        Empleado empleado = new Empleado();
        empleado.getNombre();
        String expect= "Josele";
        String actual= empleado.setNombre("Josele");
        Assert.assertEquals(expect,actual);
    }

    @Test
    public void empleadoClasificacion(){
        Empleado empleado = new Empleado();
        empleado.Clasificacion(28);
        int expect = empleado.Clasificacion(28);
        int actual = 28;
        Assert.assertEquals(actual,expect);
    }

    @Test
    public void empleadoSalario(){
        Empleado empleado = new Empleado();
        empleado.setSalario(5000);
        double expect=2500;
        double atual=empleado.aumentoSalario(5000, 50);
        Assert.assertEquals(expect,atual);
    }

    @Test
    public void programadorTest(){
        Programador programador = new Programador();
        String expect= "Java";
        String actual= programador.setLenguajeDominante("Java");
        Assert.assertEquals(actual,expect);
    }
}