/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class StudentTest {
    @Test public void testSomeLibraryMethod() {
        Estudiante estudiante = new Estudiante(, 90,"Marvin","Fernadez","9506285", 23);
        actual = "Marvin";
        expect = estudiante.getNombre();
        assertEquals(expect, actual);
    }
}
