/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class EstudianteTest {
    @Test
    public void estudiante() {
        Estudiante estudiante = new Estudiante("Marvin","Fernandez","9506285",23);
        Materia materia1 = new Materia("Lenguajes de Programacion","SIS302",100);
        Materia materia2 = new Materia("Ingles I","SIS302",100);
        Materia materia3 = new Materia("Proyectos II","ECO303",100);

        List<Materia> m = new ArrayList<>();
        m.add(materia1);
        m.add(materia2);
        m.add(materia3);

        String expect = ("ECO303" +"\n"+ "Proyectos II" +"\n"+ 100);
        String actual = estudiante.getMateria("ECO303",m);
        Assert.assertEquals(expect, actual);

    }

    @Test
    public void estudianteNota(){
        Estudiante estudiante = new Estudiante("Marvin","Fernandez","9506285",23);
        Materia materia1 = new Materia("Lenguajes de Programacion","SIS302",100);

        List<Materia> m = new ArrayList<>();
        m.add(materia1);

        int expect= (100);
        int actual= estudiante.notaMinima("SIS302",100,m);
        Assert.assertEquals(expect,actual);
    }
}
