/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class libroTest {
    @Test
    public void test_PrestamoLibro() {
        Libro l1 = new Libro("Introduccion a programacion","Joyanes Aguilar",10,2);
        int expect = l1.prestamo_Libro(10,2);
        int actual = 1;
        Assert.assertEquals(expect,actual);
    }

    @Test
    public void test_PrestamoLibro_Failure() {
        Libro l1 = new Libro("Introduccion a programacion","Joyanes Aguilar",10,2);
        int expect = l1.prestamo_Libro(2,3);
        int actual = 1;
        Assert.assertEquals(expect,actual);
    }

    @Test
    public void test_devolucionLibro(){
        Libro l1 = new Libro("Introduccion a programacion","Joyanes Aguilar",10,2);
        int expect = l1.devolucion_Libro(12,2);
        int actual = -1;
        Assert.assertEquals(expect,actual);
    }

}
