/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;



public class PartusaTest {
    @Test
    public void partusaTest() {
    }
}