/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class UniversidadTest {
    @Test
    public void testDatos() {

        Materia materia = new Materia("Lenguajes Programacion","402",100);
        List<Materia> m = new ArrayList<>();
        m.add(materia);

        Persona persona = new Persona("Marvin","Fernandez","9506285");
        Estudiante estudiante = new Estudiante("Marvin","Fernandez","9506285","Ingenieria de Sistemas", m);
        Docente docente = new Docente("Tania","Lopez","000000","Lenguajes Programacion","Ingenieria de Sistemas");
        estudiante.verDatos();
    }

    @Test
    public void testNota(){
        Materia materia = new Materia("Lenguajes Programacion","402",100);
        List<Materia> m = new ArrayList<>();
        m.add(materia);

        Estudiante estudiante = new Estudiante("Marvin","Fernandez","9506285","Ingenieria de Sistemas", m);
        Docente docente = new Docente("Tania","Lopez","000000","Lenguajes Programacion","Ingenieria de Sistemas");
        int actual = 100;
        int expect= materia.notaMinima("402",100,m);
        Assert.assertEquals(actual,expect);
    }

    @Test
    public void testDocente(){
        Materia materia = new Materia("Lenguajes Programacion","402",100);
        List<Materia> m = new ArrayList<>();
        m.add(materia);

        Estudiante estudiante = new Estudiante("Marvin","Fernandez","9506285","Ingenieria de Sistemas", m);
        Docente docente = new Docente("Tania","Lopez","000000","Lenguajes Programacion","Ingenieria de Sistemas");
        docente.datos();
    }
}
